### ISSUE TITLE
findWindowHandle won't work when the title is set via binding

### ISSUE THREAD

**Issue by GandalfTheWhite80** [mimoguz/custom_window#3]
The method findWindowHandle  is not working when the titleProperty is set via binding.

One idea: check if titleProperty.isBound() and throw an execption 

Another idea: provide a second method for this case:

```java
public static WindowHandle findWindowHandle(final Stage stage, final StringBinding titleBinding) {
        if (Platform.getOSType() != Platform.WINDOWS) {
            return null;
        }

        final var searchString = "stage_" + java.util.UUID.randomUUID();
        if (stage.titleProperty().isBound()) {
            Objects.requireNonNull(titleBinding, "TitleBinding must not be null");

            stage.titleProperty().unbind(); // unbind current binding
            stage.setTitle(searchString); // still use the search string for a unique id

            final var hwnd = User32.INSTANCE.FindWindow(null, stage.getTitle());
            stage.titleProperty().bind(titleBinding); // reset the binding

            if (hwnd != null) {
                return new WindowHandle(hwnd);
            }
        } else {
            final var title = stage.getTitle();
            stage.setTitle(searchString);
            final var hwnd = User32.INSTANCE.FindWindow(null, searchString);
            stage.setTitle(title);

            if (hwnd != null) {
                return new WindowHandle(hwnd);
            }
        }

        return null;
    }
```

**Comment by mimoguz** [comment]
Thanks, i will look into it. Though i should mention there are better alternatives now:
[https://github.com/dukke/FXThemes](https://github.com/dukke/FXThemes)
[https://github.com/xdsswar/shared-fx-jni-src](https://github.com/xdsswar/shared-fx-jni-src)

**Comment by GandalfTheWhite80** [comment]
Well at least FXThemes will need to add --add-opens/--add-exports to your vm plus you can only change the gui "after" show. You version do not have such problems :-).

**Comment by mimoguz** [comment]
😃 
The fix (*try*Find method now throws an exception) in the 0.2 branch. Not yet tested.

**Comment by mimoguz** [comment]
New version is now the main branch. Be warned that I used this opportunity to remove the dash from the artifact id and the underscore from the package name.
